version: 2
updates:
- package-ecosystem: npm
  directory: "/readmyage"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ionic-native/status-bar"
    versions:
    - 5.28.0
    - 5.31.1
    - 5.32.0
  - dependency-name: "@ionic/storage"
    versions:
    - 2.3.1
    - 3.0.2
  - dependency-name: "@angular/platform-browser"
    versions:
    - 10.0.8
    - 11.2.2
    - 11.2.3
    - 11.2.4
  - dependency-name: ionicons
    versions:
    - 5.4.0
    - 5.5.0
  - dependency-name: "@angular/core"
    versions:
    - 10.0.10
