sudo: false
os: osx
osx_image: xcode9
node_js:
  - "lts/*"
language: objective-c

before_install:
  - brew update

install: 
  - npm install -g npm
  - npm install -g cordova ionic
  - brew cask install fastlane

script:
  - cd readmyage
  - npm install
  - ionic resources
  - ionic cordova prepare
  - ionic build ios --device --debug