sudo: true
os: osx
osx_image: xcode9.3
node_js:
  - "8"
language: objective-c

matrix:
  fast_finish: true
  include:
    - env: PLATFORM='android'
      language: android
      os: linux
      android:
        components:
        - tools
        - platform-tools
        - build-tools-19.1.0
        - android-22
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19
      before_script:
        - gem install fastlane --pre
        - apt install -y graphicsmagick
    - env: PLATFORM='ios'
      language: objective-c
      os: osx
      before_script:
        - sudo gem install fastlane
        - brew install graphicsmagick
      
before_install:
  - rvm install 2.4.1
  - rvm use 2.4.1
  - nvm install 8
  - nvm use 8
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - yes | sdkmanager "platforms;android-26" || true

install:
  - sudo npm install ionic-resources -g 
  - npm install -g npm
  - npm install -g cordova ionic

script:
  - cd readmyage
  - ../setversion.py 0.0.1 $TRAVIS_BUILD_NUMBER config.xml
  - npm install
  - ionic cordova platform add $PLATFORM
  - ionic login $IONIC_EMAIL $IONIC_PASS
  - ionic-resources || true
  - ionic cordova resources || true
  - ionic cordova prepare || true
  - ionic build
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ../scripts/release-$PLATFORM.sh; fi