sudo: false
os: osx
osx_imqge: xcode9
language: objective-c

before_install:
  - brew update

install: 
  - npm install -g npm
  - npm install -g cordova ionic
  - brew cask install fastlane

script:
  - cd readmyage
  - ionic state restore
  - ionic build ios --device --debug