sudo: true
os: osx
osx_image: xcode8.3
node_js:
  - "lts/*"
language: objective-c

before_install:
  - brew update
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install: 
  - npm install -g npm
  - npm install -g cordova ionic
  - sudo gem install fastlane

script:
  - cd readmyage
  - npm install
  - ionic login $IONIC_EMAIL $IONIC_PASS
  - ionic cordova resources
  - ionic cordova prepare
  - ionic build
  - ionic cordova build ios --developmentTeam Q2465CX346
  - fastlane beta