sudo: true
os: osx
osx_image: xcode8
node_js:
  - "lts/*"
language: objective-c

before_install:
  - rvm install 2.4.1
  - rvm use 2.4.1
  - ./fix-cert.sh
  - nvm install 8
  - nvm use 8
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install: 
  - npm install -g npm
  - npm install -g cordova ionic
  - sudo gem install fastlane

script:
  - export FL_PROJECT_SIGNING_FORCE_UPGRADE=true
  - cd readmyage
  - ../setversion.py 0.0.1 $TRAVIS_BUILD_NUMBER config.xml
  - npm install
  - ionic login $IONIC_EMAIL $IONIC_PASS
  - ionic cordova resources
  - ionic cordova prepare
  - ionic build
  - fastlane add_plugin update_project_codesigning
  - fastlane setup
  - fastlane beta