sudo: true
os: osx
osx_image: xcode8
node_js:
  - "8"
language: objective-c

matrix:
  fast_finish: true
  include:
    - env: PLATFORM='android'
      language: android
      os: linux
      android:
        components:
        - tools
        - platform-tools
        - build-tools-19.1.0
        - android-22
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19
      before_script:
        - gem install fastlane --pre
    - env: PLATFORM='ios'
      language: objective-c
      os: osx
      before_script:
        - sudo gem install fastlane
      
before_install:
  - rvm install 2.4.1
  - rvm use 2.4.1
  - nvm install 8
  - nvm use 8
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install: 
  - npm install -g npm
  - npm install -g cordova ionic

script:
  - cd readmyage
  - ../setversion.py 0.0.1 $TRAVIS_BUILD_NUMBER config.xml
  - npm install
  - ionic login $IONIC_EMAIL $IONIC_PASS
  - ionic cordova resources
  - ionic cordova prepare
  - ionic build
  - ../scripts/release-$PLATFORM.sh